# Generated by Django 4.1.7 on 2023-03-21 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subcategory',
            old_name='tittle',
            new_name='category',
        ),
        migrations.AddField(
            model_name='subcategory',
            name='title',
            field=models.CharField(default=42, max_length=200),
            preserve_default=False,
        ),
    ]
